### ISSUE TITLE
Humanizer.Core 2.1.0 breaks compatibility with PCL Profile 259

### ISSUE THREAD

**Issue by IlSocio** [Humanizr/Humanizer#573]
Hi, 
I was using Humanizer.Core v2.0.1 within a PCL Profile 259
After upgrading to v2.1.0 the project doesn't compile anymore due to the errors below.
It seems you've upgraded Humanizer to the new NetStandard target, but it can't be referenced anymore from a PCL Profile 259

```
warning MSB3274: The primary reference "Humanizer, Version=2.1.0.0, Culture=neutral, PublicKeyToken=979442b78dfc278e, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".

error CS0246: The type or namespace name 'Humanizer' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by onovotny** [comment]
Hi,

What version of Visual Studio and what version of NuGet do you have?

The Humanizer 2.1 packages require at least NuGet 2.12 when using VS 2013 and at least 3.4 on VS 2015 Update 3.

Humanizer, and any `netstandard1.0` library, will install into a PCL 259 project.

**Comment by IlSocio** [comment]
I'm using Visual Studio 2015 - Update 3 and NuGet 3.4

According to this link:
https://xamarinhelp.com/dot-net-standard-pcl-xamarin-forms/
".NET Standard Libraries can reference Profile Based PCL’s but a Profile Based PCL can’t reference a .NET Standard Library PCL (not that I know of anyway)."

Indeed, I can't install AutoMapper:
"Could not install package 'AutoMapper 5.0.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by IlSocio** [comment]
I just created the a test-solution for this issue:
https://github.com/IlSocio/HumanizerTest

The PCL_NetStandard compiles successfully, while the PCL_259 doesn't

**Comment by onovotny** [comment]
Okay, found the root cause. First, that link is wrong. Netstandard does work with PCL 259, you can try installing System.Reactive to prove that.

Second, the real issue is that the wrong `TargetFrameworkAttribute` is on Humanizer for some reason. The value is `.NETPortable,Version=v5.0` when it should be `.NETStandard,Version=v1.0`. That's why it's failing.

**Comment by IlSocio** [comment]
Thank you Oren, understood :+1:

**Comment by MobileRez** [comment]
I am getting this as well when Using Humanizer with VSTS build host. Its the only package that fails. with error:
> "C:\a\1\s\Droid\Fuze.Droid.csproj" (PackageForAndroid target) (1) ->
> 2016-10-12T20:49:52.6316961Z        "C:\a\1\s\Fuze\Fuze.csproj" (default target) (3) ->
> 2016-10-12T20:49:52.6316961Z        (CoreCompile target) -> 
> 2016-10-12T20:49:52.6316961Z          Converters\DateConverters.cs(9,7): error CS0246: The type or namespace name 'Humanizer' could not be found (are you missing a using directive or an assembly reference?) [C:\a\1\s\Fuze\Fuze.csproj]

It also didn't start giving me this warning till I added humanizer.core

> 2016-10-12T20:49:43.7531988Z ##[warning]Task is using legacy task lib, detailed errors or warnings produced by msbuild.exe will not be logged as issues on the build summary page, project detail timeline record will not be created. 
I thought changing from nuget version 3.3.0 to version 3.5.0.1829 / 3.5.0-rtm-1829 would solve this, but It did not. 

Its working fine when debugging locally so it may be another issue, but this is currently breaking my CI and Auto Deploy builds for beta testing.

**Comment by MobileRez** [comment]
I am getting this as well when Using Humanizer with VSTS build host. Its the only package that fails. with error:
> "C:\a\1\s\Droid\Fuze.Droid.csproj" (PackageForAndroid target) (1) ->
> 2016-10-12T20:49:52.6316961Z        "C:\a\1\s\Fuze\Fuze.csproj" (default target) (3) ->
> 2016-10-12T20:49:52.6316961Z        (CoreCompile target) -> 
> 2016-10-12T20:49:52.6316961Z          Converters\DateConverters.cs(9,7): error CS0246: The type or namespace name 'Humanizer' could not be found (are you missing a using directive or an assembly reference?) [C:\a\1\s\Fuze\Fuze.csproj]

It also didn't start giving me this warning till I added humanizer.core

> 2016-10-12T20:49:43.7531988Z ##[warning]Task is using legacy task lib, detailed errors or warnings produced by msbuild.exe will not be logged as issues on the build summary page, project detail timeline record will not be created. 
I thought changing from nuget version 3.3.0 to version 3.5.0.1829 / 3.5.0-rtm-1829 would solve this, but It did not. 

Its working fine when debugging locally so it may be another issue, but this is currently breaking my CI and Auto Deploy builds for beta testing.

**Comment by onovotny** [comment]
This was a bug that they fixed in the latest VS 2015 Update 3 KB. Can you please verify that you have Update 3 *and* the latest hotfixes for it? 

https://msdn.microsoft.com/en-us/library/mt752379.aspx

You can see it listed under "Issue 12" of the 9/14/2016 update.

**Comment by IlSocio** [comment]
I just checked using the latest Update 3 and the issue is gone! Thank you Oren :)

**Comment by hazzik** [comment]
@onovotny but, shal it be still `.NETStandard,Version=v1.0`?

I think the issue with the `.targets` file inclusion.

**Comment by ChaseFlorell** [comment]
@onovotny I see this is closed, and tagged with "Next Bug Fix", but I'm not seeing a new release. What would we need to do to get this ball rolling?

**Comment by onovotny** [comment]
The issue was in VS 2015's build. Update 3 + the latest KB's fixed this.

**Comment by julesx** [comment]
I am running VS2015 Update 3  with the latest hotfix linked above and am still experiencing the issue.
